//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_UdemyEntities : DbContext
    {
        public MVC_UdemyEntities()
            : base("name=MVC_UdemyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblModulo> tblModuloes { get; set; }
        public virtual DbSet<tblOperacione> tblOperaciones { get; set; }
        public virtual DbSet<tblRol> tblRols { get; set; }
        public virtual DbSet<tblRolOperacion> tblRolOperacions { get; set; }
        public virtual DbSet<tblUsuario> tblUsuarios { get; set; }
    }
}
